### ISSUE TITLE
App crashes on grid opening

### ISSUE THREAD

**Issue by Janfred** [chteuchteu/Munin-for-Android#46]
On LineageOS 14.1, Android 7.1.2 I am not able to create grids because at the moment I want to open a grid the app crashes.

App Version: 4.1.1, installed from Play Store, together with the Features Pack

This is the adb logcat output:
```
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: Cannot instantiate class: androidx.mediarouter.app.MediaRouteActionProvider
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: java.lang.NoSuchMethodException: <init> [class android.content.Context]
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at java.lang.Class.getConstructor0(Class.java:2204)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at java.lang.Class.getConstructor(Class.java:1683)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at androidx.appcompat.view.SupportMenuInflater$MenuState.newInstance(SupportMenuInflater.java:549)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at androidx.appcompat.view.SupportMenuInflater$MenuState.readItem(SupportMenuInflater.java:423)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at androidx.appcompat.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:178)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:128)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at com.chteuchteu.munin.ui.Activity_Grid.createOptionsMenu(Activity_Grid.java:239)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at com.chteuchteu.munin.ui.MuninActivity.onCreateOptionsMenu(MuninActivity.java:72)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at android.app.Activity.onCreatePanelMenu(Activity.java:3146)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:378)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2549)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at android.os.Handler.handleCallback(Handler.java:751)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at android.os.Looper.loop(Looper.java:154)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at java.lang.reflect.Method.invoke(Native Method)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
05-13 13:42:08.857  8112  8112 W SupportMenuInflater: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
05-13 13:42:08.901  8112  8112 D AndroidRuntime: Shutting down VM
05-13 13:42:09.312  8112  8112 E AndroidRuntime: FATAL EXCEPTION: main
05-13 13:42:09.312  8112  8112 E AndroidRuntime: Process: com.chteuchteu.munin, PID: 8112
05-13 13:42:09.312  8112  8112 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.mediarouter.app.MediaRouteActionProvider.setRouteSelector(androidx.mediarouter.media.MediaRouteSelector)' on a null object reference
05-13 13:42:09.312  8112  8112 E AndroidRuntime: 	at com.chteuchteu.munin.hlpr.ChromecastHelper.createOptionsMenu(ChromecastHelper.java:404)
05-13 13:42:09.312  8112  8112 E AndroidRuntime: 	at com.chteuchteu.munin.ui.Activity_Grid.createOptionsMenu(Activity_Grid.java:253)
05-13 13:42:09.312  8112  8112 E AndroidRuntime: 	at com.chteuchteu.munin.ui.MuninActivity.onCreateOptionsMenu(MuninActivity.java:72)
05-13 13:42:09.312  8112  8112 E AndroidRuntime: 	at android.app.Activity.onCreatePanelMenu(Activity.java:3146)
05-13 13:42:09.312  8112  8112 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:378)
05-13 13:42:09.312  8112  8112 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
05-13 13:42:09.312  8112  8112 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2549)
05-13 13:42:09.312  8112  8112 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
05-13 13:42:09.312  8112  8112 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
05-13 13:42:09.312  8112  8112 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
05-13 13:42:09.312  8112  8112 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
05-13 13:42:09.312  8112  8112 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-13 13:42:09.312  8112  8112 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-13 13:42:09.312  8112  8112 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
05-13 13:42:09.312  8112  8112 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-13 13:42:09.312  8112  8112 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
05-13 13:42:09.312  8112  8112 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
05-13 13:42:09.317  1247 12037 W ActivityManager:   Force finishing activity com.chteuchteu.munin/.ui.Activity_Grid
05-13 13:42:09.327  1247 12037 W ActivityManager:   Force finishing activity com.chteuchteu.munin/.ui.Activity_Grids
```

**Comment by quentin-st** [comment]
Thanks for the bug report! I'll look onto it and get back to you ASAP.

**Comment by quentin-st** [comment]
@Janfred : could you try to disable Chromecast-related features from the app settings please?

![image](https://user-images.githubusercontent.com/1551971/67165498-141b2000-f386-11e9-94b9-21e579d7df83.png)
